### ISSUE TITLE
Replace zsh-syntax-highlighting

### ISSUE THREAD

**Issue by sobolevn** [sobolevn/dotfiles#10]
When pasting something really long into terminal, it freezes like for 10 second.
Maybe https://github.com/zdharma/fast-syntax-highlighting will solve this.

**Comment by sobolevn** [comment]
Right now it is not possible, but when https://github.com/zsh-users/zsh-syntax-highlighting/issues/434 will be closed, I can go back to this idea.

**Comment by danielshahaf** [comment]
Workaround: Set `ZSH_HIGHLIGHT_MAXLENGTH` and use `edit-command-line` from the zsh FAQ.

**Comment by sobolevn** [comment]
Thanks a lot!

**Comment by sobolevn** [comment]
Closed via https://github.com/sobolevn/dotfiles/commit/6b714c46e39b563de4adcc0899c4b4e2bbd91016

**Comment by danielshahaf** [comment]
You're welcome :-)

(FWIW: https://github.com/zsh-users/zsh-syntax-highlighting/issues/698)
