### ISSUE TITLE
file `versions.sh` is absent

### ISSUE THREAD

**Issue by data-if** [sobolevn/dotfiles#118]
got error when try to install with defaults:

```sh
/dotfiles/vscode/versions.sh: No such file or directory
```

**Comment by sobolevn** [comment]
Fixed in https://github.com/sobolevn/dotfiles/commit/4c4fab1ca56cc5facbf132210a6604f1e0fb8dd3

Thanks!

**Comment by data-if** [comment]
Tnx, ultra fast)
