### ISSUE TITLE
`cd` completions not working with `z` (zoxide) as cd

### ISSUE THREAD

**Issue by adriangalilea** [sobolevn/dotfiles#121]
Hello,

Been loving your dotfiles, and used as an inspo for the [default ones for my rpi's](https://github.com/adriangalilea/dotfiles-rpi)

However I've run into an issue:

I do like to `alias cd="z"`

When I do, your cd completion window, ceases to work, may be that I don't fully understand the mechanism.

Even if I add `z` here in `.completions`:
```bash
# complete `ls` / `cat` / etc
zstyle ':fzf-tab:complete:(\\|*/|)(ls|gls|bat|cat|cd|z|rm|cp|mv|ln|nano|code|open|tree|source):*' \
  fzf-preview \
  '_fzf_complete_realpath "$realpath"'
```

It doesn't work, any idea why could it be?

I've thought that it may be the order of imports, but I tried changing them a bit, and no luck.

P.S.: could you clarify how this work?

I tried `cd` <kbd>tab</kbd> the window displays, I select one directory, <kbd>enter</kbd> then I try <kbd>tab</kbd> and it doesn't trigger the window, so how do I select further down the tree?

**Comment by sobolevn** [comment]
Hi! Thanks a lot, I'm really pleased that you like it!

`zoxide` completion is done here:

https://github.com/sobolevn/dotfiles/blob/ed0b29c75b3a1a37c184634217cc7bd92bd2d6f2/shell/.completions#L68-L79

It is quite complex. First of all, take a look here, this is how `z` is defined: https://github.com/sobolevn/dotfiles/blob/ed0b29c75b3a1a37c184634217cc7bd92bd2d6f2/shell/.external#L59-L71

Then, redefine it to `cd` (or use both). It should work.

**Comment by adriangalilea** [comment]
Found the cause albeit a bit weird I think:

```
~  master ✔                                                                                                                                                                                           130 ⚠️
» z --version
zoxide: no match found
                                                                                                                                                                                                            
~  master ✔                                                                                                                                                                                             1 ⚠️
» zoxide --version
zoxide 0.9.4
```

Once I aliased z to zoxide then aliasing cd to z worked, I find weird that nothing was complaining when I did cd, and it even seemed to be triggering zoxide actually, but without it the completions didn't work.

Thanks!

P.S.: I tried `cd` <kbd>tab</kbd> the window displays, I select one directory, <kbd>enter</kbd> then I try <kbd>tab</kbd> and it doesn't trigger the window, so how do I select further down the tree?

could you clarify how this work?

**Comment by adriangalilea** [comment]
> P.S.: I tried `cd` tab the window displays, I select one directory, enter then I try tab and it doesn't trigger the window, so how do I select further down the tree?
> 
> could you clarify how this work?

Wait nvm, this now somehow works, but I lost the window pane on the right
<img width="1431" alt="image" src="https://github.com/user-attachments/assets/bf7cd36b-e4bf-4ae2-84b1-12fa1eb38bbc">
Any idea?

Sorry to be bothering you with this.

**Comment by adriangalilea** [comment]
Just to recap for your ease whenever you look at this:

# In this file:
https://github.com/adriangalilea/dotfiles-rpi/blob/44957b4ce7fad216f6396fdf656f3792b8261f7a/.shell/.completions#L13

## If I have them uncommented:
<img width="1429" alt="image" src="https://github.com/user-attachments/assets/18873215-3806-4e89-b1a6-0e4dda12f531">
The right window pane disappears.

## If I comment/remove line 13:
<img width="1435" alt="image" src="https://github.com/user-attachments/assets/a0be0cb2-5ceb-4b64-8503-85eb1f0106fc">
The right window pane reappears but I don't have zoxide as `cd` which is the way I like to have `cd`

Also if I try directly with `z` <kbd>tab</kbd>
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/65404cf0-3904-497f-afc8-1af93c267b48">

## The rest of the commands preserve the right pane in both cases
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/e1e645bf-368e-4c32-9670-dbae586f74d9">

**Comment by adriangalilea** [comment]
@sobolevn found it, first, I think you use `z` and `cd` separately  hence the 2 different flows, second, bat was always failing inside them causing further problems due the fact that in some systems, bat doesn't exists as is named batcat and when .zshenv loads it doesn't have the alias set, so I just aliased first line in .zshenv and  is working fine, is there any reason why you use both z and cd separately? isn't the point of zoxide that it learns your most visited directories when actually using it?

**Comment by sobolevn** [comment]
Yes, I use them separatelly. Because I am used to older `z-jump` or something, which didn't have the same features as `cd` does. So, my workflow is different for `cd` and `z`.
